set(TYRO_INC_ES2 
"Core/ES2/RAES2Context.h" 
"Core/ES2/RAES2CoreVisualEffects.h" 
"Core/ES2/RAES2IndexHardwareBuffer.h" 
"Core/ES2/RAES2OffScreenBuffer.h" 
"Core/ES2/RAES2Polyline.h" 
"Core/ES2/RAES2Polypoint.h" 
"Core/ES2/RAES2Renderable.h" 
"Core/ES2/RAES2Renderer.h" 
"Core/ES2/RAES2ShaderProgram.h" 
"Core/ES2/RAES2ShaderUniforms.h" 
"Core/ES2/RAES2Texture2D.h" 
"Core/ES2/RAES2TriMesh.h" 
"Core/ES2/RAES2VertexArray.h" 
"Core/ES2/RAES2VertexFormat.h" 
"Core/ES2/RAES2VertexHardwareBuffer.h" 
"Core/ES2/RAES2VisualEffect.h" 
"Core/ES2/RAES2VisualStates.h" 
)

set(TYRO_SRC_ES2 
"Core/ES2/RAES2Context.cpp" 
"Core/ES2/RAES2CoreVisualEffects.cpp" 
"Core/ES2/RAES2IndexHardwareBuffer.cpp" 
"Core/ES2/RAES2OffScreenBuffer.cpp" 
"Core/ES2/RAES2Polyline.cpp" 
"Core/ES2/RAES2Polypoint.cpp" 
"Core/ES2/RAES2Renderable.cpp" 
"Core/ES2/RAES2Renderer.cpp" 
"Core/ES2/RAES2ShaderProgram.cpp" 
"Core/ES2/RAES2ShaderUniforms.cpp" 
"Core/ES2/RAES2Texture2D.cpp" 
"Core/ES2/RAES2TriMesh.cpp" 
"Core/ES2/RAES2VertexArray.cpp" 
"Core/ES2/RAES2VertexFormat.cpp" 
"Core/ES2/RAES2VertexHardwareBuffer.cpp" 
"Core/ES2/RAES2VisualEffect.cpp" 
"Core/ES2/RAES2VisualStates.cpp" 
)

set(TYRO_INC_RENDERABLES 
"Core/Renderables/RAES2BBox.h" 
"Core/Renderables/RAES2DefaultPolyline.h" 
"Core/Renderables/RAES2DefaultTriMesh.h" 
#"Core/Renderables/RAES2Octree.h" 
"Core/Renderables/RAES2STLMesh.h"
"Core/Renderables/RAES2StandardMesh.h" 
)

set(TYRO_SRC_RENDERABLES 
"Core/Renderables/RAES2BBox.cpp" 
"Core/Renderables/RAES2DefaultPolyline.cpp" 
"Core/Renderables/RAES2DefaultTriMesh.cpp" 
#"Core/Renderables/RAES2Octree.cpp" 
"Core/Renderables/RAES2STLMesh.cpp" 
"Core/Renderables/RAES2StandardMesh.cpp" 
)

set(TYRO_INC_SCENE 
"Core/Scene/RANode.h" 
"Core/Scene/RASpatial.h" 
)

set(TYRO_SRC_SCENE 
"Core/Scene/RANode.cpp" 
"Core/Scene/RASpatial.cpp" 
)

set(TYRO_INC_TOOLS 
"Core/Tools/RASTLExporter.h" 
"Core/Tools/RASTLLoader.h" 
)

set(TYRO_SRC_TOOLS 
"Core/Tools/RASTLExporter.cpp" 
"Core/Tools/RASTLLoader.cpp" 
)

set(TYRO_INC_LOCAL 
"Core/GLStructures.h" 
"Core/RACamera.h" 
#"Core/RACameraOld.h" 
"Core/RAFileManager.h" 
"Core/RAFont.h" 
"Core/RAHardwareBuffer.h" 
"Core/RAIndexHardwareBuffer.h" 
"Core/RALogManager.h" 
"Core/RAMath.h" 
"Core/RASkeleton.h" 
"Core/RATexture.h" 
"Core/RATextureBuffer.h" 
"Core/RATouchable.h" 
#"Core/RATriOctree.h" 
"Core/RAVertexBufferAccessor.h" 
"Core/RAVertexHardwareBuffer.h" 
"Core/RAVisibleSet.h" 
"Core/RAiOSCamera.h" 
)

set(TYRO_SRC_LOCAL 
"Core/RACamera.cpp" 
#"Core/RACameraOld.cpp" 
"Core/RAFileManager.cpp" 
"Core/RAFont.cpp" 
"Core/RAHardwareBuffer.cpp" 
"Core/RAIndexHardwareBuffer.cpp" 
"Core/RALogManager.cpp" 
"Core/RAMath.cpp" 
"Core/RASkeleton.cpp" 
"Core/RATexture.cpp" 
"Core/RATextureBuffer.cpp" 
"Core/RATouchable.cpp" 
#"Core/RATriOctree.cpp" 
"Core/RAVertexBufferAccessor.cpp" 
"Core/RAVertexHardwareBuffer.cpp" 
"Core/RAVisibleSet.cpp" 
"Core/RAiOSCamera.cpp" 
)

set(TYRO_CORE_SRC
${TYRO_SRC_ES2}
${TYRO_SRC_RENDERABLES}
${TYRO_SRC_SCENE}
${TYRO_SRC_TOOLS}
${TYRO_SRC_LOCAL}
)